version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: faiq
      POSTGRES_PASSWORD: ukostdev123
      POSTGRES_DB: ukost_user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ukost-net

  mongo:
    image: mongo:6
    container_name: mongo
    command: ["mongod", "--replSet", "rs0"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ukost-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ukost-net

  prisma:
    image: node:20
    container_name: prisma-cli
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - ukost-net
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:
  mongo_data:

networks:
  ukost-net:
